'use client';
import {useEffect,useState} from 'react';
const nav=['Visão geral','Militares','Capacitação · CDP','Treinamentos','Promoções · UP','Rebaixamentos','Registros'];
const stats=[['Militares sincronizados','—','Aguardando Roblox'],['Em capacitação','—','Nenhum dado conectado'],['Treinos realizados','—','Nenhum registro real'],['Ações registradas','—','Aguardando ativação']];
const events:string[][]=[];
type RobloxUser={id:string;username:string;avatar:string;rank?:string;rankNumber?:number;isCreator?:boolean;divisions?:Array<{id:number;name:string;role:string}>};
export default function Home(){const[active,setActive]=useState('Visão geral');const[modal,setModal]=useState(false);const[user,setUser]=useState<RobloxUser|null|undefined>(undefined);useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(x=>setUser(x.user)).catch(()=>setUser(null))},[]);if(user===undefined)return <div className="auth-loading">EB DO MIG</div>;if(user===null)return <LoginPage/>;return <main className="shell">
<aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><div><b>EB DO MIG</b><small>Central Militar</small></div></div><nav><p className="nav-label">COMANDO</p>{nav.map((x,i)=><button key={x} className={'nav-item '+(active===x?'active':'')} onClick={()=>setActive(x)}><span>{['⌂','♟','◷','◆','↑','↓','▤'][i]}</span>{x}</button>)}<p className="nav-label">ADMINISTRAÇÃO</p>{['Painel do criador','Configurações'].map((x,i)=><button key={x} className={'nav-item '+(active===x?'active':'')} onClick={()=>setActive(x)}><span>{i?'⚙':'♛'}</span>{x}</button>)}</nav><div className="sidebar-foot"><i/><div><b>Sistemas operacionais</b><small>Roblox · sincronizado</small></div></div></aside>
<section className="content"><header className="topbar"><button className="search" onClick={()=>setActive('Militares')}>⌕ <span>Buscar militar, patente ou registro...</span><kbd>⌘ K</kbd></button><a className="user" href="/api/auth/logout" title="Sair"><img className="avatar" src={user.avatar} alt={`Avatar Roblox de ${user.username}`}/><div><b>{user.username}</b><small>{user.rank||'Roblox conectado'}</small></div><span>⌄</span></a></header>
<div className="page"><div className="eyebrow">— CENTRAL DE COMANDO · 26 AGO 2026</div><div className="hero"><div><h1>{active}</h1><p>Bem-vindo ao centro de operações do EB DO MIG.</p></div><div><button className="secondary" onClick={()=>setModal(true)}>Consultar militar</button><button className="primary" onClick={()=>setModal(true)}>＋ Nova ação</button></div></div>
{active==='Visão geral'?<><div className="stats">{stats.map(([l,v,d],i)=><article className="stat" key={l}><div><span>{l}</span><i>{['♟','◷','◆','▤'][i]}</i></div><strong>{v}</strong><small>{d}</small></article>)}</div>
<div className="main-grid"><article className="panel activity"><PanelHead tag="TEMPO REAL" title="Atividade recente" action="Ver todos →"/><div className="timeline">{events.length?events.map(([icon,title,desc,time,type],i)=><div className="event" key={title}><span className={'event-icon e'+i}>{icon}</span><div><b>{title}</b><p>{desc}</p><small>{time}</small></div><em>{type}</em></div>):<EmptyState text="As ações reais aparecerão após a sincronização com o Roblox."/>}</div></article>
<aside className="right"><article className="panel"><PanelHead tag="CAPACITAÇÃO" title="CDP encerrando" action="Ver painel"/><EmptyState text="Nenhuma capacitação sincronizada."/></article><article className="panel quick"><span className="kicker">ACESSO RÁPIDO</span><h2>Ações de comando</h2><div>{[['↑','Realizar UP'],['◆','Novo treino'],['◷','Criar CDP'],['⌕','Consultar']].map(([i,t])=><button key={t} onClick={()=>setModal(true)}><i>{i}</i><b>{t}</b></button>)}</div></article></aside></div>
<article className="panel divisions"><PanelHead tag="ORGANIZAÇÃO" title="Divisões configuradas" action="○ Aguardando Roblox"/><div className="division-list">{['EXÉRCITO','STAFF','BFE','CIE','BAC','BPE'].map(n=><div className="division" key={n}><b>{n}</b><small>— membros</small><div><i style={{width:'0%'}}/></div></div>)}</div></article></>:<WorkspaceView active={active} onAction={()=>setModal(true)}/>}</div></section>{modal&&<ActionModal close={()=>setModal(false)}/>}</main>}
function PanelHead({tag,title,action}:{tag:string,title:string,action:string}){return <div className="panel-head"><div><span className="kicker">{tag}</span><h2>{title}</h2></div><button>{action}</button></div>}
function LoginPage(){return <main className="login-page"><div className="login-particles"><div className="login-particle" style={{left:'15%',background:'var(--accent)',boxShadow:'0 0 5px var(--accent)',animationDelay:'0s'}}/><div className="login-particle" style={{left:'35%',background:'var(--accent)',boxShadow:'0 0 5px var(--accent)',animationDelay:'4s'}}/><div className="login-particle" style={{left:'60%',background:'var(--accent)',boxShadow:'0 0 5px var(--accent)',animationDelay:'7s'}}/><div className="login-particle" style={{left:'82%',background:'var(--accent)',boxShadow:'0 0 5px var(--accent)',animationDelay:'2.5s'}}/><div className="login-particle" style={{left:'48%',background:'var(--gold)',boxShadow:'0 0 5px var(--gold)',animationDelay:'9.5s'}}/></div><section className="login-card"><span className="corner-tl"/><span className="corner-tr"/><span className="corner-bl"/><span className="corner-br"/><img className="login-emblem" src="/og.png" alt="EB DO MIG"/><span className="login-kicker">⚡ Sistema do Exército Brasileiro</span><h1>Acesso à<br/><strong>Central Militar</strong></h1><p>EB DO MIG · Sistema de gestão e capacitação</p><a className="login-roblox" href="/api/auth/roblox/start"><span>🎮</span> Entrar com Roblox</a><div className="login-security">🔒 Acesso restrito <i/> OAuth Roblox</div><small>Ao continuar, sua patente e suas divisões serão verificadas na comunidade oficial.</small></section><footer>EB DO MIG · GRUPO 521106467</footer></main>}
function EmptyState({text}:{text:string}){return <div className="empty-state"><span>◇</span><b>Nenhum dado real disponível</b><p>{text}</p></div>}
function WorkspaceView({active,onAction}:{active:string,onAction:()=>void}){const cfg:Record<string,[string,string,string[]]>={
'Militares':['EFETIVO','Consulta de militares',[]],
'Capacitação · CDP':['CAPACITAÇÃO','CDPs em andamento',[]],
'Treinamentos':['ACADEMIA','Treinos de patente',[]],
'Promoções · UP':['CARREIRA','Promoções militares',[]],
'Rebaixamentos':['DISCIPLINA','Relatórios de rebaixamento',[]],
'Registros':['AUDITORIA','Registros protegidos',[]],
'Painel do criador':['ACESSO MÁXIMO','Painel do criador',['Patentes e hierarquia','Divisões e grupos Roblox','Permissões e integrações']],
'Configurações':['SISTEMA','Configurações',['Integração Roblox · Aguardando credenciais','Discord e webhooks · Aguardando canal','Segurança e permissões · Preparadas']]};const[tag,title,rows]=cfg[active]||cfg.Militares;return <div className="workspace-grid"><article className="panel workspace"><div className="workspace-toolbar"><div><span className="kicker">{tag}</span><h2>{title}</h2></div><button className="primary" onClick={onAction}>＋ Nova ação</button></div><label className="workspace-search">⌕ <input placeholder="Pesquisar por nome, ID ou patente"/></label><div className="records">{rows.length?rows.map((row,i)=><button key={row}><span className="record-avatar">{row.slice(0,2).toUpperCase()}</span><div><b>{row.split(' · ')[0]}</b><small>{row.split(' · ').slice(1).join(' · ')}</small></div><em>{i===1?'EM ANDAMENTO':'ATIVO'}</em><strong>→</strong></button>):<EmptyState text="Os registros aparecerão aqui quando a integração estiver ativa."/>}</div></article><aside className="panel help"><span className="kicker">CONTROLE SEGURO</span><h2>Permissões preparadas</h2><p>Todas as ações serão validadas conforme a patente, CDP ativo e cargo do responsável.</p><ul><li>Login oficial Roblox</li><li>Registros permanentes</li><li>Regras no servidor</li></ul></aside></div>}
function ActionModal({close}:{close:()=>void}){const[done,setDone]=useState(false);return <div className="modal-wrap" role="dialog" aria-modal="true"><button className="scrim" onClick={close} aria-label="Fechar"/><div className="modal">{done?<><span className="success">✓</span><h2>Ação preparada</h2><p>O fluxo foi aberto com sucesso. A alteração real será enviada ao Roblox após a conexão das credenciais.</p><button className="close filled" onClick={close}>Concluir</button></>:<><span className="kicker">NOVA OPERAÇÃO</span><h2>Selecione uma ação</h2><p>A permissão e o CDP serão verificados novamente antes da confirmação.</p>{['↑ Realizar promoção / UP','◆ Registrar treinamento','◷ Iniciar capacitação · CDP','↓ Registrar rebaixamento'].map(x=><button key={x} onClick={()=>setDone(true)}>{x}<span>→</span></button>)}<button className="close" onClick={close}>Cancelar</button></>}</div></div>}
