'use client';
import {useState} from 'react';
import Link from 'next/link';
const nav=['Visão geral','Militares','Capacitação · CDP','Treinamentos','Promoções · UP','Rebaixamentos','Registros'];
const stats=[['Militares sincronizados','47','Última sincronização há 2min'],['Em capacitação','12','CDP #047 em andamento'],['Treinos realizados','23','Este mês'],['Ações registradas','156','Desde Janeiro']];
const events=[['↑','Sargento Silva → 3º Tenente','Promoção aprovada pelo criador','há 2 horas','PROMOÇÃO'],['◆','Treino de tiro — BFE','8 participantes, nota média 8.5','há 5 horas','TREINO'],['↓','Cabo Mendes — advertência','Rebaixamento por falta de assiduidade','ontem','REBAIXAMENTO'],['ZR','Patente verificada — Sgt. Costa','Verificação automática via Roblox','ontem','SISTEMA']];
type RobloxUser={id:string;username:string;avatar:string;rank?:string;rankNumber?:number;isCreator?:boolean;divisions?:Array<{id:number;name:string;role:string}>};
const mockUser:RobloxUser={id:'1',username:'ComandanteEB',avatar:'',rank:'[CR] Criador',rankNumber:255,isCreator:true,divisions:[{id:1,name:'EXÉRCITO',role:'Comandante'},{id:2,name:'STAFF',role:'Admin'}]};

export default function Preview(){
  const[active,setActive]=useState('Visão geral');
  const[modal,setModal]=useState(false);
  const user=mockUser;
  const goToLogin=()=>window.location.href='/';
  return <main className="shell">
<aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><div><b>EB DO MIG</b><small>Central Militar</small></div></div><nav><p className="nav-label">COMANDO</p>{nav.map((x,i)=><button key={x} className={'nav-item '+(active===x?'active':'')} onClick={()=>setActive(x)}><span>{['⌂','♟','◷','◆','↑','↓','▤'][i]}</span>{x}</button>)}<p className="nav-label">ADMINISTRAÇÃO</p>{['Painel do criador','Configurações'].map((x,i)=><button key={x} className={'nav-item '+(active===x?'active':'')} onClick={()=>setActive(x)}><span>{i?'⚙':'♛'}</span>{x}</button>)}</nav><div className="sidebar-foot"><i/><div><b>Sistemas operacionais</b><small>Roblox · sincronizado</small></div></div></aside>
<section className="content"><header className="topbar"><button className="search" onClick={()=>setActive('Militares')}>⌕ <span>Buscar militar, patente ou registro...</span><kbd>⌘ K</kbd></button><Link className="user" href="/" title="Fazer login"><div style={{width:34,height:34,borderRadius:8,background:'#1a2a1a',display:'grid',placeItems:'center',color:'var(--accent)',fontSize:12,fontWeight:700}}>CE</div><div><b>{user.username}</b><small>{user.rank}</small></div><span>⌄</span></Link></header>
<div className="page"><div className="eyebrow">— MODO PREVIEW · <a href="/" style={{color:'var(--accent)',textDecoration:'underline'}}>FAÇA LOGIN PARA USAR</a></div><div className="hero"><div><h1>{active}</h1><p>Bem-vindo ao centro de operações do EB DO MIG.</p></div><div><Link href="/" className="primary" style={{textDecoration:'none'}}>🔑 Fazer login com Roblox</Link></div></div>
{active==='Visão geral'?<><div className="stats">{stats.map(([l,v,d],i)=><article className="stat" key={l}><div><span>{l}</span><i>{['♟','◷','◆','▤'][i]}</i></div><strong>{v}</strong><small>{d}</small></article>)}</div>
<div className="main-grid"><article className="panel activity"><PanelHead tag="TEMPO REAL" title="Atividade recente" action="Ver todos →"/><div className="timeline">{events.map(([icon,title,desc,time,type])=><div className="event" key={title}><span className="event-icon">{icon}</span><div><b>{title}</b><p>{desc}</p><small>{time}</small></div><em>{type}</em></div>)}</div></article>
<aside className="right"><article className="panel"><PanelHead tag="CAPACITAÇÃO" title="CDP encerrando" action="Ver painel"/><EmptyState text="Nenhuma capacitação sincronizada."/></article><article className="panel quick"><span className="kicker">ACESSO RÁPIDO</span><h2>Ações de comando</h2><div>{[['↑','Realizar UP'],['◆','Novo treino'],['◷','Criar CDP'],['⌕','Consultar']].map(([i,t])=><button key={t} onClick={goToLogin}><i>{i}</i><b>{t}</b></button>)}</div></article></aside></div>
<article className="panel divisions"><PanelHead tag="ORGANIZAÇÃO" title="Divisões configuradas" action="○ 6 divisões"/><div className="division-list">{[['EXÉRCITO','23'],['STAFF','8'],['BFE','5'],['CIE','4'],['BAC','4'],['BPE','3']].map(([n,c])=><div className="division" key={n}><b>{n}</b><small>{c} membros</small><div><i style={{width:`${(parseInt(c)/23)*100}%`}}/></div></div>)}</div></article></>:<WorkspaceView active={active} onAction={goToLogin}/>}</div></section>{modal&&<ActionModal close={()=>setModal(false)} onLogin={goToLogin}/>}</main>}

function PanelHead({tag,title,action}:{tag:string,title:string,action:string}){return <div className="panel-head"><div><span className="kicker">{tag}</span><h2>{title}</h2></div><button>{action}</button></div>}
function EmptyState({text}:{text:string}){return <div className="empty-state"><span>◇</span><b>Nenhum dado real disponível</b><p>{text}</p></div>}
function WorkspaceView({active,onAction}:{active:string,onAction:()=>void}){const cfg:Record<string,[string,string,string[]]>={
'Militares':['EFETIVO','Consulta de militares',['Sgt. Silva · 3º Tenente','Cabo Mendes · Soldado','Sgt. Costa · Sgt.']],
'Capacitação · CDP':['CAPACITAÇÃO','CDPs em andamento',['CDP #047 · Liderança','CDP #048 · Tiro']],
'Treinamentos':['ACADEMIA','Treinos de patente',['Tiro — BFE · 8 participantes','Navegação — CIE · 5 participantes']],
'Promoções · UP':['CARREIRA','Promoções militares',['Sgt. Silva → 3º Tenente','Sold. Almeida → Cabo']],
'Rebaixamentos':['DISCIPLINA','Relatórios de rebaixamento',['Cabo Mendes · advertência']],
'Registros':['AUDITORIA','Registros protegidos',['Patente verificada — Sgt. Costa','Login — ComandanteEB']],
'Painel do criador':['ACESSO MÁXIMO','Painel do criador',['Patentes e hierarquia','Divisões e grupos Roblox','Permissões e integrações']],
'Configurações':['SISTEMA','Configurações',['Integração Roblox · Ativa','Discord e webhooks · Configurar','Segurança e permissões · Preparadas']]};const[tag,title,rows]=cfg[active]||cfg.Militares;return <div className="workspace-grid"><article className="panel workspace"><div className="workspace-toolbar"><div><span className="kicker">{tag}</span><h2>{title}</h2></div><button className="primary" onClick={onAction}>＋ Nova ação</button></div><label className="workspace-search">⌕ <input placeholder="Pesquisar por nome, ID ou patente"/></label><div className="records">{rows.length?rows.map((row,i)=><button key={row}><span className="record-avatar">{row.split(' · ')[0].slice(0,2).toUpperCase()}</span><div><b>{row.split(' · ')[0]}</b><small>{row.split(' · ').slice(1).join(' · ')}</small></div><em>{i===1?'EM ANDAMENTO':'ATIVO'}</em><strong>→</strong></button>):<EmptyState text="Os registros aparecerão aqui quando a integração estiver ativa."/>}</div></article><aside className="panel help"><span className="kicker">CONTROLE SEGURO</span><h2>Permissões preparadas</h2><p>Todas as ações serão validadas conforme a patente, CDP ativo e cargo do responsável.</p><ul><li>Login oficial Roblox</li><li>Registros permanentes</li><li>Regras no servidor</li></ul></aside></div>}
function ActionModal({close,onLogin}:{close:()=>void,onLogin:()=>void}){return <div className="modal-wrap" role="dialog" aria-modal="true"><button className="scrim" onClick={close} aria-label="Fechar"/><div className="modal"><span className="kicker">LOGIN NECESSÁRIO</span><h2>Faça login para executar ações</h2><p>Esta é uma visualização do painel. Para realizar promoções, treinos e outros registros, é necessário entrar com sua conta Roblox.</p><a href="/" className="primary" style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8,width:'100%',marginTop:12,textDecoration:'none'}}>🎮 Entrar com Roblox</a><button className="close" onClick={close}>Voltar ao preview</button></div></div>}
